name: Run tests for lesson 8

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/url-checker.ts'
      - 'tests/url-checker.test.ts'

  push:
    branches:
      - main
    paths:
      - 'src/url-checker.ts'
      - 'tests/url-checker.test.ts'


jobs:
  autotests-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set up dependencies
        run: npm ci
        working-directory: HW8


      - name: Run tests
        run: npm test
        working-directory: HW8

