name: Build and Test

on:
  push:
    branches:
      - HW_13
  pull_request:
    branches:
      - HW_13

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
            compose-file: ./docker-compose.yaml
            up-flags: -d

      - name: Run empty users test first
        run: npx playwright test tests/users-empty.test.ts

      - name: Run all other tests
        run: npx playwright test --exclude tests/users-empty.test.ts
