name: HW13
on:
  push:
    branches:
      - HW13_new
    paths:
      - 'tests/DTO/UserDTO'
      - 'tests/users-array-tests.test.ts'
      - 'tests/user-controller.test.ts'
      - 'tests/users-empty.test.ts'
  pull_request:
    branches:
      - HW13_new
    paths:
      - 'tests/DTO/UserDTO'
      - 'tests/users-array-tests.test.ts'
      - 'tests/user-controller.test.ts'
      - 'tests/users-empty.test.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: HW13


      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
            compose-file: ./docker-compose.yaml
            up-flags: -d


      - run: npx playwright install --with-deps
        working-directory: HW13

      - name: Run empty users test first
        run: npx playwright test ./tests/users-empty.test.ts

      - name: Run all other tests
        run: npx playwright test --exclude ./tests/users-empty.test.ts
