name: HW13

on:
  push:
    branches:
      - HW13_clean
  pull_request:
    branches:
      - HW13_clean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js (LTS 20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости внутри HW13
      - name: Install dependencies
        run: npm install
        working-directory: HW13

      # 4. Устанавливаем Playwright и браузеры
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: HW13

      # 5. Поднимаем Docker Compose
      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./HW13/docker-compose.yaml
          up-flags: -d

      # 6. Запуск теста с пустыми пользователями
      - name: Run empty users test first
        run: npx playwright test tests/users-empty.test.ts
        working-directory: HW13

      # 7. Запуск остальных тестов
      - name: Run all other tests
        run: npx playwright test "tests/!(users-empty).test.ts"
        working-directory: HW13
