name: Playwright Tests

on:
  push:
    branches:
      - HW_16
    paths:
      - 'HW16/src/order-flow.html'
      - 'HW16/tests/local-component-tests.spec.ts'
      - 'HW16/tests/auth-tests.spec.ts'
      - 'HW16/tests/example.spec.ts'

  pull_request:
    branches:
      - HW_16
    paths:
      - 'HW16/src/order-flow.html'
      - 'HW16/tests/local-component-tests.spec.ts'
      - 'HW16/tests/auth-tests.spec.ts'
      - 'HW16/tests/example.spec.ts'


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: HW16
    
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: HW16

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: HW16

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
