name: Run tests for lesson 8

on:
  pull_request:
    branches:
      - main
    paths:
      - 'hw8/src/password.ts'
      - 'hw8/tests/password.test.ts'
  push:
    branches:
      - main
    paths:
      - 'src/password.ts'
      - 'tests/password.test.ts'

jobs:
  autotests-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set up dependencies
        run: npm install

      - name: Run tests
        run: npm run test-right-now1
